# comment
label GetExample
https://example.com
GET /

---

set URL http://localhost:8080

delay 5s

label PostThing
${URL}
Content-Type: application/json
POST /user
{
  "user": "taybart",
  "11": 12,
}

---

skip

label SkippedThing
${URL}
GET /user
