request "get auth token" {
  url = "http://localhost:18080/auth"
  method = "POST"
  body = {
    "username": "root",
    "password": "root"
  }
  post_hook = <<LUA
    print('==='..rest.label..'===')
    local body = json.decode(rest.res.body)
    rest.exports.auth_token = body.auth_token
  LUA
}
request "use exports" {
  url = "http://localhost:18080/"
  bearer_token = "${exports.auth_token}"
  post_hook = <<LUA
    print('\n==='..rest.label..'===')
    print(inspect(rest.req.headers['Authorization']['1']))
  LUA
}

server {
  address = "localhost:18080"
  response {
    status = 200
    body = {
      auth_token = "this_is_an_auth_token"
    }
  }
}
