request "get auth token" {
  url = "http://localhost:18080/auth"
  method = "POST"
  body = {
    "username": "root",
    "password": "root"
  }
  post_hook = <<LUA
    print('==='..rest.label..'===')
    local body = json.decode(rest.res.body)
    if not body.auth_token  then
      fail('no auth_token returned')
      return
    end
    rest.exports.auth_token = body.auth_token
    print('got new auth_token: '..rest.exports.auth_token)
  LUA
}

request "use exports" {
  url = "http://localhost:18080/test"
  bearer_token = exports.auth_token
  post_hook = <<LUA
    print('\n==='..rest.label..'===')
    local auth_header, other = tools.get_req_header('Authorization')
    if  auth_header ~= "Bearer this_is_an_auth_token" then
      print(auth_header, other)
      fail('missing or incorrect auth_token')
      return
    end
    print(inspect(json.decode(rest.res.body)))
  LUA
}

request "unknown route" {
  url = "http://localhost:18080/unknown"
  bearer_token = exports.auth_token
  expect = 404
  post_hook = <<LUA
    print('\n==='..rest.label..'===')
    if not tools.is_expected_response() then
      return
    end
    print(rest.res.dump)
  LUA
}


server {
  address = "localhost:18080"
  handler "POST" "/auth" {
    # method  = "POST"
    response {
      status = 200
      headers = { "Content-Type" = "application/json" }
      body = { auth_token:  "this_is_an_auth_token" }
    }
  }
  handler "GET" "/test" {
    # method  = "GET"
    fn = <<LUA
      print('auth header: '..tools.get_req_header('Authorization'))
      if tools.get_req_header('Authorization') ~= "Bearer this_is_an_auth_token" then
        return 
        end
      return 200, json.encode({ hello =  "world" })
    LUA
  }
  # response {
  #   status = 200
  # }
}
