locals {
  imported = "HELLO"
  testTmpl = <<JSON
  {
    "hello": "{{.WORLD}}"
  }
  JSON
}

request "base" {
  skip = true
  url = "http://localhost:8500"
  method = "POST"
  bearer_token = "test"
  body = tmpl(locals.testTmpl, {WORLD = "world"})
  post_hook = <<LUA
    print('label: '..rest.label)
  LUA
}
