request "lua check" {
  url = "http://localhost:18080/__echo__"
  after = <<LUA
    print(rest.res.dump)
    local body = json.decode(rest.res.body)
    inspect.print(body.test.second)
  LUA
}

server { address = "127.0.0.1:18080" }
