config {skip_imported = true}
locals {
  imported = "HELLO"
  testTmpl = <<JSON
  {
    "hello": "{{.WORLD}}"
  }
  JSON
}

request "base" {
  # skip = true
  url = "http://localhost:18080"
  method = "POST"
  bearer_token = "test"
  body = tmpl(locals.testTmpl, {WORLD = "world"})
  after = <<LUA
    if rest.label == "base" then
      error("should not have executed base")
    end
    print('label: '..rest.label)
  LUA
}
