# start a server with `rest -s -a :18080`

request "basic auth" {
  url = "http://localhost:18080/hello-world"
  method = "POST"
  # TODO: make this a block OR string
  basic_auth = "user:password"
  headers = {
    "Content-Type" = "application/json"
  }
  body = {
    data: "hello world"
  }
}

locals {
  token = "ey..."
}

request "bearer token" {
  url = "https://localhost:18080/hello-world"
  method = "POST"
  bearer_token = locals.token
  headers = {
    "Content-Type" = "application/json"
    "X-Custom-Header" = "custom-header"
  }
  body = {
    data: "hello world"
  }
}

request "bearer token as header" {
  url = "https://localhost:18080/hello-world"
  method = "POST"
  headers = {
    "Authorization" = "Bearer ${locals.token}"
    "Content-Type" = "application/json"
  }
  body = {
    data: "hello world"
  }
}
