config {
  # no_follow_redirect = true
  no_cookies = true
}

locals {
  url = "https://httpbin.org"
}

// test
request "post hook get" {
  url = "${locals.url}/cookies/set"
  method = "GET"
  headers = [ "X-Test: test" ]
  query = { b = "2" }
  body = { test: "body" }
  cookies = { a = "1" }
  post_hook = <<LUA
    print('from lua below:')
    for k, v in pairs(rest.res.cookies) do
      print(k..'='..v)
    end
  LUA
}
request "clean get" {
  url = "${locals.url}/get"
  post_hook = <<LUA
    print('from lua below:')
    for k, v in pairs(rest.res.cookies) do
      print(k..'='..v)
    end
    -- print('req: '..inspect(rest.req))
    -- print('res: '..inspect(rest.res))
  LUA
}
