locals {
  # url = "http://localhost:8089"
  url = "https://httpbin.org"
  name = "world"
  hook = <<LUA
    print("\n"..rest.req.method.." "..rest.req.url)
    if rest.req.expect then
      if rest.res.status ~= rest.req.expect then
        fail(("bad status %d != %d"):format(rest.res.status, rest.req.expect))
      end
    end
    local decoded = json.decode(rest.res.body)
    if decoded.json then
      return inspect(decoded.json)
    elseif decoded.args then
      return ("test plus 70 = %d"):format(decoded.args.test + 70)
    end
  LUA
}

// test
request "post hook get" {
  url = "${locals.url}/get"
  query = {
    test = 1
    "other[friend]" = 3
  }
  method = "GET"
  post_hook = <<LUA
    local decoded = json.decode(rest.res.body)
      print(inspect(decoded.args))
      print(inspect(rest.req))
    if decoded.args then
      return ("\ntest plus 70 => %d"):format(decoded.args.test + 70)
    end
  LUA
}

request "post hook post" {
  url = "${locals.url}/post"
  method = "POST"
  headers = [
    "X-TEST: you:😄",
    "Content-Type: application/json",
  ]
  body = {
    name: "test"
    hello: "${locals.name}"
    test: 17
  }
  expect = 201
  post_hook = "${locals.hook}"
}
