// todo: add snippets to rest.nvim
server {
  address = "localhost:18080"
  cors = true
  response {
    status = 200
    headers = {
      "x-custom-header": "custom-header",
      "x-env-header": env("HEADER_VALUE")
    }
    body = {
      "custom": "response"
    }
  }
}
