cli = <<LUA
local conversation = {}
while true do
	io.write("> ")
	local prompt = io.read()
	if prompt == "echo" then
		inspect.print(conversation)
		goto continue
	end
	table.insert(conversation, { role = "user", content = prompt })
	rest.exports.conversation = json.encode(conversation)
	-- os.setenv('conversation', json.encode(conversation))
	rest.label("completions")
	table.insert(conversation, { role = "assistant", content = rest.exports.response })
	-- check we are exporting correctly
	rest.label("test")
	::continue::
end
LUA


request "completions" {
  # url = "http://localhost:8585/api/v1/chat/completions"
  url = "http://localhost:11434/v1/chat/completions"
  method = "POST"
  headers = { "Content-Type" = "application/json" }
  body = {
    model: "gemma3:4b",
    messages: json_dec(try_exports("conversation", env("conversation")))
  }
  after = <<LUA
    local body = json.decode(rest.res.body)
    -- inspect.print(rest.req.body)
    local response = body.choices[1].message.content
    rest.exports.response = response
    -- check we are exporting correctly
    if rest.exports.test then
    	rest.exports.test = rest.exports.test .. "doesthiswork"
    else
    	rest.exports.test = "doesthiswork"
    end
    print(response)
  LUA
}

request "test" {
  url = "http://localhost:18080/${exports.test}"
}

server {
  address = "0.0.0.0:18080"
}
